# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sbednar <sbednar@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/21 23:40:02 by sbednar           #+#    #+#              #
#    Updated: 2019/02/16 22:04:52 by sbednar          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME 		=	libft.a

SRC_DIR		=	./src
OBJ_DIR		=	./obj

SRC			=	ft_strlen.c \
				ft_strcmp.c \
				ft_strdup.c \
				ft_strcpy.c \
				ft_strncpy.c \
				ft_strcat.c \
				ft_strncat.c \
				ft_strlcat.c \
				ft_strchr.c \
				ft_strrchr.c \
				ft_strstr.c \
				ft_strnstr.c \
				ft_strncmp.c \
				ft_strnew.c \
				ft_strdel.c \
				ft_strsdel.c \
				ft_strclr.c \
				ft_striter.c \
				ft_striteri.c \
				ft_strmap.c \
				ft_strmapi.c \
				ft_strequ.c \
				ft_strnequ.c \
				ft_strsub.c \
				ft_strjoin.c \
				ft_strtrim.c \
				ft_strsplit.c \
				ft_checkdlm.c \
				ft_checkdlms.c \
				ft_dlmscount.c \
				ft_getwrdlen.c \
				ft_getwrd.c \
				ft_wrdscount.c \
				ft_memset.c \
				ft_bzero.c \
				ft_memcpy.c \
				ft_memccpy.c \
				ft_memmove.c \
				ft_memchr.c \
				ft_memcmp.c \
				ft_memalloc.c \
				ft_memdel.c \
				ft_putchar.c \
				ft_putstr.c \
				ft_putendl.c \
				ft_putnbr.c \
				ft_putchar_fd.c \
				ft_putstr_fd.c \
				ft_putendl_fd.c \
				ft_putnbr_fd.c \
				ft_lstnew.c \
				ft_lstdelone.c \
				ft_lstdel.c \
				ft_lstfree.c \
				ft_lstadd.c \
				ft_lstiter.c \
				ft_lstmap.c \
				ft_isalpha.c \
				ft_isdigit.c \
				ft_isalnum.c \
				ft_isascii.c \
				ft_isprint.c \
				ft_toupper.c \
				ft_tolower.c \
				ft_atoi.c \
				ft_itoa.c \
				ft_swap.c \
				get_next_line.c \
				ft_i_love_u_peer.c

OBJ			=	$(addprefix $(OBJ_DIR)/,$(SRC:.c=.o))

CC 			=	gcc
CFLAGS		=	-Wall -Werror -Wextra

all: $(NAME)

$(NAME): $(OBJ_DIR) $(OBJ)
	ar rc $(NAME) $(OBJ)
	ranlib $(NAME)

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

$(OBJ_DIR)/%.o:$(SRC_DIR)/lst/%.c
	$(CC) $(CFLAGS) -I. -o $@ -c $<

$(OBJ_DIR)/%.o:$(SRC_DIR)/mem/%.c
	$(CC) $(CFLAGS) -I. -o $@ -c $<

$(OBJ_DIR)/%.o:$(SRC_DIR)/oth/%.c
	$(CC) $(CFLAGS) -I. -o $@ -c $<

$(OBJ_DIR)/%.o:$(SRC_DIR)/out/%.c
	$(CC) $(CFLAGS) -I. -o $@ -c $<

$(OBJ_DIR)/%.o:$(SRC_DIR)/str/%.c
	$(CC) $(CFLAGS) -I. -o $@ -c $<

clean:
	rm -rf $(OBJ_DIR)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
